site_name: ""
site_description: "A comprehensive wiki for The Artifact universe."
site_author: "Jake Gibbons"
site_url: https://your-domain.com         # (optional) set when you go live
repo_url: https://github.com/yourorg/artifact-wiki
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  logo: assets/images/artifact-logo.svg
  favicon: assets/images/favicon.ico
  palette:
    - scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: "Roboto Mono, monospace"
    code: "Fira Code, monospace"
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.action.edit
    - header.autohide
  icon:
    repo: fontawesome/brands/github

extra_css:
  - assets/css/custom-overrides.css        # define additional theme tweaks here

extra:
  social:
    - icon: fontawesome/solid/rocket
      link: /series-overview/
      name: Dive in
    - icon: fontawesome/solid/atom
      link: /worldbuilding/
      name: Worldbuilding

copyright: Copyright &copy; 2025 Jake Gibbons

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Series:
      - Overview: series-overview.md
      - Season Summaries: season-summaries.md
      - Arc Chart: series-arc-chart.md
  - Characters:
      - Main Characters:
          - Lyra Quen: lyra-quen.md
      - Profiles: character-profiles.md
      - Virell Dane: characters/virell-dane.md
  - Worldbuilding:
      - Artifact & Architects: artifact-architects.md
      - Dual Timeline: dual-timeline.md
      - Earth as Ceremonial World: earth-ceremonial-world.md
      - Expanded Worldbuilding: expanded-worldbuilding.md
      - Timeline of the Universe: timeline-universe.md
      - Worlds:
          - Novasol Prime: planets/novasol-prime.md
          - Ferros: planets/ferros.md
          - Serenos: planets/serenos.md
          - Myrath: planets/myrath.md
          - Oura Station: planets/oura-station.md
          - Earth: planets/earth.md
  - Factions & Politics:
      - Council Violations: law/council-violation-system.md
      - Political Structure: factions-politics.md
      - Factions:
          - The Enlightened: factions/enlightened.md
          - The Veil: factions/veil.md
          - The Council: factions/council.md
          - Bureau of Knowledge: factions/bureau-of-knowledge.md
          - Bureau of Security: factions/bureau-of-security.md
          - Bureau of Population: factions/bureau-of-population.md
          - Bureau of Culture: factions/bureau-of-culture.md
          - Bureau of Expansion: factions/bureau-of-expansion.md
          - Council Compliance Authority (CCA): factions/cca.md
          - Architects: factions/architects.md
  - Concepts & Technology:
      - Unity Creed: concepts/unity-creed.md
      - Slipstream Gate: technology/slipstream-gate.md
  - Locations & Events:
      - Echo Archives: locations/echo-archives.md
      - Proclamation of Ascendancy: events/proclamation-of-ascendancy.md
  - Themes:
      - Legacy & Trauma: legacy-trauma.md
  - Visual References: visual-references.md
