site_name: The Artifact
site_description: "A comprehensive wiki for The Artifact universe."
site_author: "Jake Gibbons"
site_url: https://your-domain.com         # (optional) set when you go live
repo_url: https://github.com/yourorg/artifact-wiki
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  logo: assets/images/artifact-logo.svg
  favicon: assets/images/favicon.ico
  palette:
    - scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: "Roboto Mono, monospace"
    code: "Fira Code, monospace"
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.action.edit
    - header.autohide
  icon:
    repo: fontawesome/brands/github

extra_css:
  - assets/css/custom-overrides.css        # define additional theme tweaks here

extra:
  social:
    - icon: fontawesome/solid/rocket
      link: /series-overview/
      name: Dive in
    - icon: fontawesome/solid/atom
      link: /worldbuilding/
      name: Worldbuilding

copyright: Copyright &copy; 2025 Jake Gibbons

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Series Overview: series-overview.md
  - Season Summaries: season-summaries.md
  - Series Arc Chart: series-arc-chart.md
  - Characters:
      - Lyra Quen: lyra-quen.md
      - Character Profiles: character-profiles.md
  - Worldbuilding:
      - Artifact & Architects: artifact-architects.md
      - Dual Timeline: dual-timeline.md
      - Earth as Ceremonial World: earth-ceremonial-world.md
      - Expanded Worldbuilding: expanded-worldbuilding.md
      - Timeline of the Universe: timeline-universe.md
  - Factions & Politics:
      - Council Violations: council-violations.md
      - Factions & Political Structure: factions-politics.md
      - Factions:
          - The Enlightened: factions/enlightened.md
          - The Veil: factions/veil.md
          - The Council: factions/council.md
  - Themes:
      - Legacy & Trauma: legacy-trauma.md
  - Visual References: visual-references.md
  - Worlds:
      - Novasol Prime: worlds/novasol-prime.md
      - Ferros: worlds/ferros.md
      - Serenos: worlds/serenos.md
      - Myrath: worlds/myrath.md
      - Oura Station: worlds/oura-station.md
      - Earth: worlds/earth.md
