site_name: The Artifact Wiki
theme:
  name: material
nav:
  - Home: index.md
  - Storyline:
      - Overview: storyline/overview.md
      - Season 1: storyline/season1.md
      - Season 2: storyline/season2.md
      - Season 3: storyline/season3.md
      - Season 4: storyline/season4.md
      - Season 5: storyline/season5.md
  - Factions:
      - The Veil: factions/the_veil.md
      - The Enlightened: factions/the_enlightened.md
      - The Continuum: factions/the_continuum.md
      - The Guardians: factions/the_guardians.md
      - The Council: factions/the_council.md
  - World:
      - Novasol Prime: world/novasol_prime.md
      - The Vault: world/the_vault.md
      - Antarctica: world/antarctica.md
  - Characters:
      - Main Scientist: characters/main_scientist.md
  - Lore:
      - The Architects: lore/architects.md
      - Artifact Origin: lore/artifact_origin.md
      - Final Scene: lore/final_scene.md
  - Quotes & Symbols:
      - Proclamations: quotes/proclamations.md
      - Mottos: quotes/mottos.md